version: '3'
# name: camino
services:

  camino-back:
    build:
      context: .
      dockerfile: Dockerfile.back
    # image: idockerapi      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /home/sadmin/Work/mounts/export:/export
      # - /home/sadmin/Work/mounts/weights:/weights
      # - /home/sadmin/Documents/images/inputs:/inputs
      # - /home/sadmin/Documents/images/projects_data:/projects_data
    ports:
      - "8003:80"
    container_name: camino-back-new
    networks:
      - camino-net 

networks:
  camino-net:
    #driver: bridge
    name: camino-net
    attachable: true