version: '3'
# name: camino
services:

  camino-back:
    build:
      context: .
      dockerfile: Dockerfile.back
    # image: idockerapi      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/Documents/back/export:/export
    ports:
      - "8003:80"
    container_name: camino-back-new
    networks:
      - camino-net 

networks:
  camino-net:
    #driver: bridge
    name: camino-net
    attachable: true